import type { JestConfigWithTsJest } from 'ts-jest';

const config: JestConfigWithTsJest = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': [
      'ts-jest',
      {
        tsconfig: {
          baseUrl: '.',
          paths: {
            '@/*': ['src/*'],
            '@core': ['src/core'],
            '@core/*': ['src/core/*'],
            '@core/http': ['src/core/client-http'],
            '@core/response': ['src/core/response'],
            '@agent': ['src/agent'],
            '@agent/*': ['src/agent/*'],
            '@wecom': ['src/wecom'],
            '@wecom/*': ['src/wecom/*'],
            '@shared': ['src/shared'],
            '@shared/*': ['src/shared/*'],
            '@test-suite': ['src/test-suite'],
            '@test-suite/*': ['src/test-suite/*'],
            '@core/supabase': ['src/core/supabase'],
            '@db': ['src/db'],
            '@db/*': ['src/db/*'],
            '@db/config': ['src/db/config'],
            '@db/user': ['src/db/user'],
            '@db/agent': ['src/db/agent'],
            '@db/message': ['src/db/message'],
            '@db/monitoring': ['src/db/monitoring'],
            '@db/test-suite': ['src/db/test-suite'],
          },
        },
      },
    ],
  },
  collectCoverageFrom: ['**/*.(t|j)s'],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  preset: 'ts-jest',
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
    '^@core/http$': '<rootDir>/core/client-http',
    '^@core/response$': '<rootDir>/core/response',
    '^@core$': '<rootDir>/core',
    '^@core/(.*)$': '<rootDir>/core/$1',
    '^@agent$': '<rootDir>/agent',
    '^@agent/(.*)$': '<rootDir>/agent/$1',
    '^@wecom$': '<rootDir>/wecom',
    '^@wecom/(.*)$': '<rootDir>/wecom/$1',
    '^@shared$': '<rootDir>/shared',
    '^@shared/(.*)$': '<rootDir>/shared/$1',
    '^@test-suite$': '<rootDir>/test-suite',
    '^@test-suite/(.*)$': '<rootDir>/test-suite/$1',
    '^@core/supabase$': '<rootDir>/core/supabase',
    '^@db/config$': '<rootDir>/db/config',
    '^@db/user$': '<rootDir>/db/user',
    '^@db/agent$': '<rootDir>/db/agent',
    '^@db/message$': '<rootDir>/db/message',
    '^@db/monitoring$': '<rootDir>/db/monitoring',
    '^@db/test-suite$': '<rootDir>/db/test-suite',
    '^@db$': '<rootDir>/db',
  },
};

export default config;
