import { RedisKeyBuilder } from '@wecom/message/runtime/redis-key.util';

// 环境隔离由 RedisService.withPrefix 负责，本工具产出无 env 段
const SCOPE = 'wecom:message';

describe('RedisKeyBuilder', () => {
  describe('dedup', () => {
    it('should return correct dedup key format', () => {
      expect(RedisKeyBuilder.dedup('msg_123456')).toBe(`${SCOPE}:dedup:msg_123456`);
    });

    it('should handle empty messageId', () => {
      expect(RedisKeyBuilder.dedup('')).toBe(`${SCOPE}:dedup:`);
    });

    it('should handle messageId with special characters', () => {
      expect(RedisKeyBuilder.dedup('msg-abc_123:xyz')).toBe(`${SCOPE}:dedup:msg-abc_123:xyz`);
    });

    it('should not include any env segment (handled by RedisService)', () => {
      expect(RedisKeyBuilder.dedup('test')).toBe(`${SCOPE}:dedup:test`);
    });
  });

  describe('pending', () => {
    it('should return correct pending key format', () => {
      expect(RedisKeyBuilder.pending('chat_abc')).toBe(`${SCOPE}:pending:chat_abc`);
    });

    it('should handle empty chatId', () => {
      expect(RedisKeyBuilder.pending('')).toBe(`${SCOPE}:pending:`);
    });

    it('should handle chatId with various formats', () => {
      expect(RedisKeyBuilder.pending('wxid_abc123def456')).toBe(
        `${SCOPE}:pending:wxid_abc123def456`,
      );
    });
  });

  describe('history', () => {
    it('should return correct history key format', () => {
      expect(RedisKeyBuilder.history('chat_abc')).toBe(`${SCOPE}:history:chat_abc`);
    });

    it('should handle empty chatId', () => {
      expect(RedisKeyBuilder.history('')).toBe(`${SCOPE}:history:`);
    });

    it('should handle chatId with numbers and letters', () => {
      expect(RedisKeyBuilder.history('room_12345')).toBe(`${SCOPE}:history:room_12345`);
    });
  });

  describe('lock', () => {
    it('should return correct lock key format', () => {
      expect(RedisKeyBuilder.lock('chat_abc')).toBe(`${SCOPE}:lock:chat_abc`);
    });

    it('should handle empty chatId', () => {
      expect(RedisKeyBuilder.lock('')).toBe(`${SCOPE}:lock:`);
    });
  });

  describe('pattern', () => {
    it.each(['dedup', 'pending', 'history', 'lock'] as const)(
      'should return correct %s pattern',
      (type) => {
        expect(RedisKeyBuilder.pattern(type)).toBe(`${SCOPE}:${type}:*`);
      },
    );
  });

  describe('modulePrefix', () => {
    it('should return module prefix', () => {
      expect(RedisKeyBuilder.modulePrefix).toBe(`${SCOPE}:`);
    });

    it('should end with a colon', () => {
      expect(RedisKeyBuilder.modulePrefix).toMatch(/:$/);
    });
  });

  describe('key uniqueness', () => {
    it('different key types should produce different keys for the same id', () => {
      const id = 'same_id';
      const keys = [
        RedisKeyBuilder.dedup(id),
        RedisKeyBuilder.pending(id),
        RedisKeyBuilder.history(id),
        RedisKeyBuilder.lock(id),
      ];
      expect(new Set(keys).size).toBe(4);
    });

    it('pattern should match keys generated by corresponding method', () => {
      const chatId = 'chat_001';
      const historyKey = RedisKeyBuilder.history(chatId);
      const patternPrefix = RedisKeyBuilder.pattern('history').replace('*', '');
      expect(historyKey.startsWith(patternPrefix)).toBe(true);
    });
  });
});
